parameters:
    assetic.twig_extension.class: ITE\JsBundle\Twig\Extension\AsseticExtension

services:
    assetic.twig_extension:
        class: %assetic.twig_extension.class%
        public: false
        arguments: [@assetic.asset_factory, @templating.name_parser, %assetic.use_controller%, %assetic.twig_extension.functions%, %assetic.bundles%, @?assetic.value_supplier]
        tags:
            - { name: twig.extension }
            - { name: assetic.templating.twig }