parameters:
    ite_js.twig.extension.link.class:   ITE\JsBundle\Twig\Extension\LinkExtension
    ite_js.event.listener.csrf.class:   ITE\JsBundle\EventListener\CsrfListener

services:
    ite_js.twig.extension.link:
        class: %ite_js.twig.extension.link.class%
        arguments: [ @security.csrf.token_manager ]
        tags:
            - { name: twig.extension }

    ite_js.event.listener.csrf:
        class: %ite_js.event.listener.csrf.class%
        arguments: [ @security.csrf.token_manager ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: -1 }