parameters:
    ite_js.sf.class:                    ITE\JsBundle\SF\SF
    ite_js.event.listener.ajax.class:   ITE\JsBundle\EventListener\AjaxListener
    ite_js.twig.extension.sf.class:     ITE\JsBundle\Twig\Extension\SFExtension
    ite_js.assetic.sf_resource.class:   ITE\JsBundle\Assetic\Factory\Resource\SFResource
    ite_js.assetic.sf_loader.class:     ITE\JsBundle\Assetic\Factory\Loader\SFLoader

services:
    ite_js.sf:
        class: %ite_js.sf.class%
        arguments: [ @service_container ]

    ite_js.event.listener.ajax:
        class: %ite_js.event.listener.ajax.class%
        arguments: [ @ite_js.sf ]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -255 }
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 256 }

    ite_js.twig.extension.sf:
        class: %ite_js.twig.extension.sf.class%
        arguments: [ @ite_js.sf ]
        tags:
            - { name: twig.extension }

    ite_js.assetic.sf_resource:
        class: %ite_js.assetic.sf_resource.class%
        arguments: [ @ite_js.sf ]
        public: false
        tags:
            - { name: assetic.formula_resource, loader: sf }

    ite_js.assetic.sf_loader:
        class: %ite_js.assetic.sf_loader.class%
        tags:
            - { name: assetic.formula_loader, alias: sf }